import Direction from '../../../../graphs/classes/Direction';
import { unfold, findBed } from '../foldTestBootstrap';
import { describeComputationReferenceOutput } from '../../../../../test-utils/computationFixtures';

// "Layer A" of the fold-test coverage strategy (see development-roadmap/part-a-pr-plan.md):
// lock the *deterministic core* of the bootstrap fold test — `findBed` + `unfold` — which
// carry all the science (bedding derivation, fractional untilting, the T-matrix eigenvalue
// search for the best-unfolding percentage) and contain NO randomness, NO React.Dispatch,
// NO timers. The stochastic shell (`drawBootstrap` resampling, the setTimeout pump, the
// localStorage/Dispatch result delivery) is exactly the part that still needs the Step-3
// refactor before it can be reference-tested; this layer pins the math underneath it now,
// so any future refactor (Vite, Zustand, a web-worker/Rust port) that perturbs the core
// shows up as a red diff instead of a silent, plausible-looking change in a random output.
//
// Input: a seeded, synthetically-folded dataset generated by scripts/gen_foldtest.py — a
// tight Fisher cluster of "stratigraphic" (pre-fold) directions, re-folded site-by-site with
// PmagPy's `dotilt` so the geographic directions are scattered and the TRUE best-unfolding
// answer is ~100 % (full unfolding recovers the tight cluster). The adapter rebuilds the
// production setup exactly: cartesian geographic vector + bedding (azimuth/dip) derived from
// the geo↔strat rotation via `findBed`, then runs `unfold` over the −50…150 % grid. Output:
// { index (best-unfolding %), taus ([{x: untilt %, y: t1}]) }.
//
// The locked `index` is 98 %, and 98 rather than 100 is the correct answer for this input,
// not a rounding artifact: it is the finite-sample optimum of this N=18 draw, and PmagPy on a
// 1 % grid lands on 98 too. `unfold` hones in on a 1 % grid, so it resolves the peak that the
// 10 % grid in synthetic_fold.pmagpy.json (which reports 100 %) cannot.
//
// These numbers changed in SCI-01 (September 2026). Until then the fixture locked
// index = −17 % with tau1 *falling* 0.61 → 0.44 where PmagPy's rose — a confirmed PMTools
// defect, locked as-is under the Part A golden-master discipline (see found-bugs-todo.md,
// "Surfaced in Layer A"): `findBed` returns a dip direction (`azimuth = strike + 90`), and
// `unfold` fed it straight into `Coordinates.correctBedding`, whose first parameter is a
// *strike* (it computes `dipDirection = strike + 90` itself). The 90 degrees went in twice,
// so every fractional untilting rotated about an axis 90° away from the fold axis and
// clustering peaked near 0 %. The two conventions agree exactly at 0 % unfolding, which is
// why it hid for four years. The PmagPy cross-check is what exposed it — a plain
// golden-master would have silently enshrined −17 % as "correct".
//
// The curve here is the locked regression net; the *properties* it is meant to have (PmagPy
// parity within 5e-4 across the grid, component-wise round trips including overturned beds)
// live next door in foldTestUnfoldAxis.test.ts.
//
// The `iteration` argument only gates whether the per-step taus curve is captured
// (`iteration < 24`); `index` is computed regardless. Two cases lock both branches:
//   - iteration 0  → full taus curve saved;
//   - iteration 24 → taus stays empty, only the index is reported.
describeComputationReferenceOutput({
  name: 'unfold (fold-test deterministic core)',
  fixtureDirectory: 'fold_unfold',
  invoke: (input) => {
    const vectors = (
      input.directions as Array<{
        Dgeo: number;
        Igeo: number;
        Dstrat: number;
        Istrat: number;
      }>
    ).map((direction) => {
      const geographic = new Direction(direction.Dgeo, direction.Igeo, 1).toCartesian();
      const stratigraphic = new Direction(direction.Dstrat, direction.Istrat, 1).toCartesian();
      const bedding = findBed(geographic, stratigraphic);
      return {
        coordinates: geographic,
        beddingAzimuth: bedding.azimuth,
        beddingDip: bedding.dip,
      };
    });
    return unfold(vectors, input.iteration);
  },
});
