import Direction from '../../../../graphs/classes/Direction';
import { unfold, findBed } from '../foldTestBootstrap';
import { describeComputationReferenceOutput } from '../../../../../test-utils/computationFixtures';

// "Layer A" of the fold-test coverage strategy (see development-roadmap/part-a-pr-plan.md):
// lock the *deterministic core* of the bootstrap fold test — `findBed` + `unfold` — which
// carry all the science (bedding derivation, fractional untilting, the T-matrix eigenvalue
// search for the best-unfolding percentage) and contain NO randomness, NO React.Dispatch,
// NO timers. The stochastic shell (`drawBootstrap` resampling, the setTimeout pump, the
// localStorage/Dispatch result delivery) is exactly the part that still needs the Step-3
// refactor before it can be reference-tested; this layer pins the math underneath it now,
// so any future refactor (Vite, Zustand, a web-worker/Rust port) that perturbs the core
// shows up as a red diff instead of a silent, plausible-looking change in a random output.
//
// Input: a seeded, synthetically-folded dataset generated by scripts/gen_foldtest.py — a
// tight Fisher cluster of "stratigraphic" (pre-fold) directions, re-folded site-by-site with
// PmagPy's `dotilt` so the geographic directions are scattered and the TRUE best-unfolding
// answer is ~100 % (full unfolding recovers the tight cluster; on the 10 % untilting grid
// both PMTools and PmagPy use, PmagPy's fold test peaks at 100 %, tau1 0.61 → 0.96 — a finer
// grid lands at ~98 % from the 0.1° rounding). The adapter rebuilds the production setup
// exactly: cartesian geographic vector + bedding (azimuth/dip) derived from the geo↔strat
// rotation via `findBed`, then runs `unfold` over the −50…150 % grid. Output:
// { index (best-unfolding %), taus ([{x: untilt %, y: t1}]) }.
//
// ⚠️ The locked `index` is −17 %, NOT the true 100 %. This is a CONFIRMED PMTools bug, locked
// as-is (golden-master regression net, the Part A discipline — see found-bugs-todo.md
// "Surfaced in Layer A"): `findBed` returns a dip-direction (`azimuth = strike + 90`), but
// `unfold` feeds it straight into `Coordinates.correctBedding`, whose first parameter is a
// *strike* (it computes `dipDirection = strike + 90` itself). The 90° mismatch unfolds about
// the wrong axis, so clustering is maximized near 0 %. The PmagPy cross-check is what exposed
// this — a plain golden-master would have silently enshrined −17 % as "correct". When the
// convention bug is fixed, this fixture goes red and must be regenerated to ~100 %.
//
// The `iteration` argument only gates whether the per-step taus curve is captured
// (`iteration < 24`); `index` is computed regardless. Two cases lock both branches:
//   - iteration 0  → full taus curve saved;
//   - iteration 24 → taus stays empty, only the index is reported.
describeComputationReferenceOutput({
  name: 'unfold (fold-test deterministic core)',
  fixtureDirectory: 'fold_unfold',
  invoke: (input) => {
    const vectors = (
      input.directions as Array<{
        Dgeo: number;
        Igeo: number;
        Dstrat: number;
        Istrat: number;
      }>
    ).map((direction) => {
      const geographic = new Direction(direction.Dgeo, direction.Igeo, 1).toCartesian();
      const stratigraphic = new Direction(direction.Dstrat, direction.Istrat, 1).toCartesian();
      const bedding = findBed(geographic, stratigraphic);
      return {
        coordinates: geographic,
        beddingAzimuth: bedding.azimuth,
        beddingDip: bedding.dip,
      };
    });
    return unfold(vectors, input.iteration);
  },
});
